import { DropdownMenu } from '@kobalte/core/dropdown-menu'
import { createSignal, For } from 'solid-js'
import { toast } from '~/components/feedback/toast'
import { Icon } from '~/components/ui/Icon'
import { Spinner } from '~/components/ui/Primitives'
import { getErrorMessage } from '~/services/api'
import { examsApi, type ExportKind } from '~/services/exams.api'
import { saveBlob } from '~/utils/download'

const items: { kind: ExportKind; label: string; hint: string }[] = [
  { kind: 'export/pdf', label: 'Exam paper (PDF)', hint: 'Print-ready, no answers' },
  { kind: 'export/word', label: 'Exam paper (Word)', hint: 'Editable .docx' },
  { kind: 'answer-key/pdf', label: 'Answer key (PDF)', hint: 'Confidential' },
  { kind: 'answer-key/word', label: 'Answer key (Word)', hint: 'Confidential' },
]

/** Downloads exam/answer-key documents generated by the API (PDF via QuestPDF, Word via OpenXML). */
export function ExportMenu(props: { examId: string; disabled?: boolean }) {
  const [busy, setBusy] = createSignal(false)

  const download = async (kind: ExportKind) => {
    setBusy(true)
    try {
      const { blob, fileName } = await examsApi.download(props.examId, kind)
      saveBlob(blob, fileName)
    } catch (err) {
      toast.error('Export failed', getErrorMessage(err))
    } finally {
      setBusy(false)
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenu.Trigger
        disabled={props.disabled || busy()}
        class="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50 disabled:cursor-not-allowed disabled:text-slate-400"
      >
        {busy() ? <Spinner class="size-4" /> : <Icon name="download" />}
        Export
        <DropdownMenu.Icon><Icon name="down" class="size-3.5" /></DropdownMenu.Icon>
      </DropdownMenu.Trigger>
      <DropdownMenu.Portal>
        <DropdownMenu.Content class="z-50 min-w-[14rem] rounded-lg border border-slate-200 bg-white p-1 shadow-lg outline-none">
          <For each={items}>
            {(item) => (
              <DropdownMenu.Item
                class="flex cursor-pointer flex-col rounded-md px-3 py-2 text-sm outline-none data-[highlighted]:bg-slate-100"
                onSelect={() => download(item.kind)}
              >
                <span class="font-medium text-slate-900">{item.label}</span>
                <span class="text-xs text-slate-500">{item.hint}</span>
              </DropdownMenu.Item>
            )}
          </For>
        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu>
  )
}
